# Generated by Django 4.0.1 on 2022-02-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
            ],
            options={
                'verbose_name': 'Gerente',
                'verbose_name_plural': 'Gerentes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'admin'), (1, 'customer'), (2, 'manager')], default=0, editable=False, verbose_name='Tipo de usuário'),
        ),
    ]
