# Generated by Django 4.0.1 on 2022-02-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('city', models.CharField(max_length=50, verbose_name='Cidade')),
                ('cnpj', models.CharField(max_length=20, verbose_name='CNPJ')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this company should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Ativo?')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro')),
            ],
        ),
    ]
