# Generated by Django 4.0.1 on 2022-02-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_manager'),
        ('company', '0002_company_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='manager',
        ),
        migrations.AddField(
            model_name='company',
            name='manager',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Manager', verbose_name='Gerente'),
        ),
    ]
